INSERT INTO admins (name, email, role) VALUES ('andrei', 'andrei@gmail.com', 'admin');

INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Florin Lazar', 'student', 'florin.lazar02@e-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.7, 2, 'Andrei Popescu', 'student', 'andrei.popescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Maria Ionescu', 'student', 'maria.ionescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.5, 2, 'Ion Vasilescu', 'student', 'ion.vasilescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.3, 2, 'Elena Dumitrescu', 'student', 'elena.dumitrescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.5, 2, 'Mihai Georgescu', 'student', 'mihai.georgescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.8, 2, 'Raluca Stanescu', 'student', 'raluca.stanescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.9, 2, 'Alexandru Radu', 'student', 'alexandru.radue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.0, 2, 'Gabriela Marin', 'student', 'gabriela.marine-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.6, 2, 'Cristina Popa', 'student', 'cristina.popae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.4, 2, 'Vlad Dumitru', 'student', 'vlad.dumitrue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.2, 2, 'Ioana Matei', 'student', 'ioana.mateie-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.5, 2, 'Paul Rusu', 'student', 'paul.rusue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.2, 2, 'Andreea Ilie', 'student', 'andreea.iliee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.1, 2, 'Stefan Vlad', 'student', 'stefan.vlade-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.0, 2, 'Monica Constantinescu', 'student', 'monica.constantinescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.8, 2, 'Razvan Ene', 'student', 'razvan.enee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.7, 2, 'Iulia Munteanu', 'student', 'iulia.munteanue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.5, 2, 'Adrian Neagu', 'student', 'adrian.neague-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.3, 2, 'Laura Dobre', 'student', 'laura.dobree-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.0, 2, 'Cristian Barbu', 'student', 'cristian.barbue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.9, 2, 'Diana Lupu', 'student', 'diana.lupue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.4, 2, 'Marius Pop', 'student', 'marius.pope-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.1, 2, 'Carmen Voicu', 'student', 'carmen.voicue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.2, 2, 'Lucian Dumitrache', 'student', 'lucian.dumitrachee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.3, 2, 'Anca Tudor', 'student', 'anca.tudore-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.9, 2, 'Gabriel Pana', 'student', 'gabriel.panae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.4, 2, 'Oana Suciu', 'student', 'oana.suciue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.6, 2, 'Dragos Radu', 'student', 'dragos.radue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.6, 2, 'Madalina Petrache', 'student', 'madalina.petrachee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.6, 2, 'Florina Sandu', 'student', 'florina.sandue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.7, 2, 'Nicoleta Popescu', 'student', 'nicoleta.popescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Costin Ionescu', 'student', 'costin.ionescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.5, 2, 'Mihai Iliescu', 'student', 'mihai.iliescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.3, 2, 'Corina Dumitrescu', 'student', 'corina.dumitrescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.5, 2, 'Anca Georgescu', 'student', 'anca.georgescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.8, 2, 'Alina Stan', 'student', 'alina.stane-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.9, 2, 'Dragos Radu', 'student', 'dragos.radue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.0, 2, 'Oana Vlad', 'student', 'oana.vlade-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.6, 2, 'Cristian Marin', 'student', 'cristian.marine-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.4, 2, 'Simona Popa', 'student', 'simona.popae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.2, 2, 'Gabriel Matei', 'student', 'gabriel.mateie-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.5, 2, 'Laura Rusu', 'student', 'laura.rusue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.2, 2, 'Adrian Ilie', 'student', 'adrian.iliee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.1, 2, 'Ioana Vlad', 'student', 'ioana.vlade-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.0, 2, 'Florin Constantinescu', 'student', 'florin.constantinescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.8, 2, 'Raluca Ene', 'student', 'raluca.enee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.7, 2, 'Andreea Munteanu', 'student', 'andreea.munteanue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.5, 2, 'Stefan Neagu', 'student', 'stefan.neague-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.3, 2, 'Monica Dobre', 'student', 'monica.dobree-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.0, 2, 'Cristina Barbu', 'student', 'cristina.barbue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.9, 2, 'Vlad Lupu', 'student', 'vlad.lupue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.8, 2, 'Ioan Lazar', 'student', 'ioan.lazare-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.4, 2, 'Daniel Pop', 'student', 'daniel.pope-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.1, 2, 'Madalina Voicu', 'student', 'madalina.voicue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.2, 2, 'Costin Dumitrache', 'student', 'costin.dumitrachee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.3, 2, 'Ana Tudor', 'student', 'ana.tudore-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.4, 2, 'Vlad Constantin', 'student', 'vlad.constantine-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.6, 2, 'Cristian Neagu', 'student', 'cristian.neague-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.7, 2, 'Elena Vlad', 'student', 'elena.vlade-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.7, 2, 'Nicoleta Radu', 'student', 'nicoleta.radue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Andrei Lupu', 'student', 'andrei.lupue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.4, 2, 'Ion Popescu', 'student', 'ion.popescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.3, 2, 'Maria Rusu', 'student', 'maria.rusue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.5, 2, 'Stefan Georgescu', 'student', 'stefan.georgescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.8, 2, 'Andreea Stan', 'student', 'andreea.stane-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.9, 2, 'Gabriel Ene', 'student', 'gabriel.enee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.0, 2, 'Florina Marin', 'student', 'florina.marine-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.6, 2, 'Cristian Popa', 'student', 'cristian.popae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.4, 2, 'Raluca Dumitru', 'student', 'raluca.dumitrue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.2, 2, 'Anca Matei', 'student', 'anca.mateie-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.5, 2, 'Ioan Rusu', 'student', 'ioan.rusue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.2, 2, 'Mihai Ilie', 'student', 'mihai.iliee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.1, 2, 'Ana Vlad', 'student', 'ana.vlade-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.0, 2, 'Monica Constantinescu', 'student', 'monica.constantinescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.8, 2, 'Razvan Ene', 'student', 'razvan.enee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.7, 2, 'Iulia Munteanu', 'student', 'iulia.munteanue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.5, 2, 'Adrian Neagu', 'student', 'adrian.neague-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.3, 2, 'Laura Dobre', 'student', 'laura.dobree-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.0, 2, 'Cristian Barbu', 'student', 'cristian.barbue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.9, 2, 'Diana Lupu', 'student', 'diana.lupue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.4, 2, 'Marius Pop', 'student', 'marius.pope-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.1, 2, 'Carmen Voicu', 'student', 'carmen.voicue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.2, 2, 'Lucian Dumitrache', 'student', 'lucian.dumitrachee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.3, 2, 'Anca Tudor', 'student', 'anca.tudore-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.9, 2, 'Gabriel Pana', 'student', 'gabriel.panae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.4, 2, 'Oana Suciu', 'student', 'oana.suciue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.6, 2, 'Dragos Radu', 'student', 'dragos.radue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.5, 2, 'Radu Constantin', 'student', 'radu.constantine-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.9, 2, 'Vasile Marian', 'student', 'vasile.mariane-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.2, 2, 'Elena Pavel', 'student', 'elena.pavele-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Sorin Andrei', 'student', 'sorin.andreie-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.3, 2, 'Mihai Teodorescu', 'student', 'mihai.teodorescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.5, 2, 'Gabriela Voinea', 'student', 'gabriela.voineae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.6, 2, 'Ionela Sandu', 'student', 'ionela.sandue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.8, 2, 'Stefan Florescu', 'student', 'stefan.florescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.3, 2, 'Raluca Dima', 'student', 'raluca.dimae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.1, 2, 'Cristian Manole', 'student', 'cristian.manolee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.4, 2, 'Irina Lupescu', 'student', 'irina.lupescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.8, 2, 'Dan Chiriac', 'student', 'dan.chiriace-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.0, 2, 'Nicoleta Avram', 'student', 'nicoleta.avrame-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.9, 2, 'George Ene', 'student', 'george.enee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.6, 2, 'Diana Oprea', 'student', 'diana.opreae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.4, 2, 'Costin Radulescu', 'student', 'costin.radulescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.3, 2, 'Luciana Cazacu', 'student', 'luciana.cazacue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.2, 2, 'Andrei Voicu', 'student', 'andrei.voicue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.7, 2, 'Alexandra Gheorghe', 'student', 'alexandra.gheorghee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.4, 2, 'Marius Petrescu', 'student', 'marius.petrescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.9, 2, 'Bianca Cojocaru', 'student', 'bianca.cojocarue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.0, 2, 'Cristina Toma', 'student', 'cristina.tomae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.7, 2, 'Bogdan Grigore', 'student', 'bogdan.grigoree-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.2, 2, 'Ionela Luca', 'student', 'ionela.lucae-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.5, 2, 'Ana Maria Vasile', 'student', 'ana.maria.vasilee-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.6, 2, 'Alexandru Neacsu', 'student', 'alexandru.neacsue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.9, 2, 'Diana Moraru', 'student', 'diana.morarue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.5, 2, 'Carmen Badescu', 'student', 'carmen.badescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 6.7, 2, 'Gheorghe Ardelean', 'student', 'gheorghe.ardeleane-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.1, 2, 'Catalina Munteanu', 'student', 'catalina.munteanue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.0, 2, 'Nicoleta Trandafir', 'student', 'nicoleta.trandafire-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.4, 2, 'Stefan Rotaru', 'student', 'stefan.rotarue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.6, 2, 'Irina Stancu', 'student', 'irina.stancue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.9, 2, 'Bogdan Diaconescu', 'student', 'bogdan.diaconescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 7.3, 2, 'Mihaela Dragomir', 'student', 'mihaela.dragomire-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 8.7, 2, 'Catalin Oncescu', 'student', 'catalin.oncescue-uvt.ro');
INSERT INTO students (facultysection, grade, studyyear, name, role, email) VALUES ('FMI_IR', 9.1, 2, 'Sorina Dobre', 'student', 'sorina.dobree-uvt.ro');

-- Cursuri pentru anul 2, capacitate variabilă între 50 și 100, distribuite în 5 categorii
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 75, 2, 'Dezvoltare Web', 'Dezvoltare Web', 'Popescu', 54);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 60, 2, 'Dezvoltare Web', 'Programare Web Avansată', 'Ionescu', 61);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 80, 2, 'Dezvoltare Web', 'Aplicatii Web', 'Georgescu', 49);

INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 50, 2, 'Inteligență Artificială', 'Inteligenta Artificiala', 'Popescu', 52);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 70, 2, 'Inteligență Artificială', 'Invatare Automata', 'Ionescu', 56);

INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 90, 2, 'Baze de Date', 'Sisteme de Baze de Date', 'Dumitrescu', 49);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 55, 2, 'Baze de Date', 'Baze de Date Avansate', 'Georgescu', 51);

INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 65, 2, 'Algoritmi și Structuri de Date', 'Structuri de Date', 'Marinescu', 50);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 85, 2, 'Algoritmi și Structuri de Date', 'Algoritmi', 'Marinescu', 55);

INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 100, 2, 'Sisteme de Operare', 'Sisteme de Operare', 'Dumitrescu', 52);

INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 100, 1, 'Logica', 'Limbaje Formale', 'Dumitrescu', 51);
INSERT INTO courses (facultysection, maxcapacity, studyyear, category, name, teacher, applicationsCount) VALUES ('FMI_IR', 100, 3, 'Logica', 'Logica Computationala', 'Dumitrescu', 60);